name: Publish Helm chart
on:
  push:
    tags:
      - '*.*.*'
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    env:
      DOCKER_LABEL: ${{ github.head_ref }}
      DOCKER_PUSH_LATEST: true
      DOCKER_REPOSITORY: renku-jena/
      HELM_URL: https://storage.googleapis.com/kubernetes-helm
      HELM_TGZ: helm-v2.17.0-linux-amd64.tar.gz
    steps:
      - uses: actions/checkout@v3
      - name: Lint chart
        uses: hiberbee/github-action-helm@latest
        with:
          helm: repo list
      - name: Lint chart
        run: helm lint helm-chart/renku-jena
        working-directory: .
      - name: Set environment variables
        run: |
          echo "GIT_USER=Renku Bot" >> $GITHUB_ENV
          echo "GIT_EMAIL=renku@datascience.ch" >> $GITHUB_ENV
      - name: Build and push chart and images
        uses: SwissDataScienceCenter/renku-actions/publish-chart@v0.5.3
        env:
          CHART_PATH: helm-chart/renku-jena
          CHART_NAME: renku-jena
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
