name: Publish Helm chart
on:
  push:
    tags:
      - '*.*.*'
jobs:
  cleanup-previous-runs:
    name: Cleanup previous runs
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        env:
          GITHUB_TOKEN: "${{ secrets.RENKUBOT_GITHUB_TOKEN }}"
  compile-compactor:
    name: Compile Compactor tool
    runs-on: ubuntu-latest
    needs: [ cleanup-previous-runs ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v1.0.6
        with:
          jvm: temurin:21
      - run: scala-cli compile compactor/src/* compactor/Compactor.scala
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ compile-compactor ]
    env:
      GIT_USER: Renku Bot
      GIT_EMAIL: renku@datascience.ch
      GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
      CHART_TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Lint chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./renku-jena/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install chartpress
      - name: Build and push chart and images
        run: |
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_USER"
          git config --global --add safe.directory /github/workspace
          echo ${{ secrets.RENKU_DOCKER_PASSWORD }} | docker login -u ${{ secrets.RENKU_DOCKER_USERNAME }} --password-stdin
          chartpress --push --publish-chart --tag "$CHART_TAG" --image-prefix renku/ --builder docker-buildx --platform linux/amd64 --platform linux/arm64
