apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "renku-jena.fullname" . }}-master
  labels:
    {{- include "renku-jena.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ include "renku-jena.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "renku-jena.selectorLabels" . | nindent 6 }}
      role: master
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "renku-jena.selectorLabels" . | nindent 8 }}
        role: master
    spec:
      initContainers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: prepare-fuseki-base-dir
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: fuseki-base
              mountPath: {{ .Values.fusekiBase }}
          command:
            - sh
            - -c
           {{- if .Values.additionalInitContainerScript  }}
            - mkdir -p {{ .Values.fusekiBase }}/configuration && echo '{{ .Values.fusekiBase }}/configuration' folder prepared && {{ .Values.additionalInitContainerScript }}
           {{- else }}
            - mkdir -p {{ .Values.fusekiBase }}/configuration && echo '{{ .Values.fusekiBase }}/configuration' folder prepared
           {{- end  }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.additionalEnvironmentVariables }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: FUSEKI_BASE
              value: {{ .Values.fusekiBase }}
          ports:
            - name: jena-http
              containerPort: 3030
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /$/ping
              port: jena-http
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /$/ping
              port: jena-http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 60
          startupProbe:
            httpGet:
              path: /$/ping
              port: jena-http
            failureThreshold: 60
            periodSeconds: 5
          volumeMounts:
            {{- with .Values.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: fuseki-base
              mountPath: {{ .Values.fusekiBase }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with .Values.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: fuseki-base
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim $ }}
        {{- else if not .Values.persistence.enabled }}
        - name: fuseki-base
          emptyDir: {}
        {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: fuseki-base
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- include "renku-jena.storage.class" (dict "persistence" .Values.persistence) | nindent 8 }}
        {{- end }}
